# Expense Manager API Requests Documentation and Tests
# ============================================

# Expense Controller

### Get all expenses
GET http://localhost:8083/expenses/
Accept: application/json

### Get a specific expense by ID (enter a correct one from the first response!)
GET http://localhost:8083/expenses/c73caa5a-26f8-4abf-989a-aa98d83826d2
Accept: application/json


### Get expenses by category ID (enter a correct one based on previous response!)
GET http://localhost:8083/expenses/category/07735d6e-1f5a-41cd-8f51-08b0acd861b5
Accept: application/json

### Create a new expense
POST http://localhost:8083/expenses/new
Content-Type: application/json

{
  "name": "Lunch",
  "description": "Lunch at a restaurant",
  "amount": 1550,
  "categoryId": "07735d6e-1f5a-41cd-8f51-08b0acd861b5"
}

### Update an existing expense
PATCH http://localhost:8083/expenses/update/f1b995b4-2ec1-421c-ad16-90515fd1c6d1
Content-Type: application/json

{
  "name": "Lunch Updated",
  "description": "Updated lunch description",
  "amount": 20.00,
  "categoryId": "80624076-a574-4ba9-ae5e-6c1824080bfb"
}

### Delete an expense
DELETE http://localhost:8083/expenses/delete/f1b995b4-2ec1-421c-ad16-90515fd1c6d1
Accept: application/json

# Expense Category Controller

### Get all expense categories
GET http://localhost:8083/categories/
Accept: application/json

### Get a specific expense category by ID
GET http://localhost:8083/categories/07735d6e-1f5a-41cd-8f51-08b0acd861b5
Accept: application/json


### Create a new expense category
POST http://localhost:8083/categories/new
Content-Type: application/json

{
  "name": "Food",
  "description": "Food-related expenses"
}

### Update an existing expense category
PATCH http://localhost:8083/categories/update/7603ac98-cc03-43bd-9ba3-eab9d75c34c6
Content-Type: application/json

{
  "name": "Food & Drink",
  "description": "Updated description for food-related expenses"
}

### Delete an expense category
DELETE http://localhost:8083/categories/delete/7603ac98-cc03-43bd-9ba3-eab9d75c34c6
Accept: application/json